services:
  jenkins:
    platform: linux/arm64
    image: jenkins/jenkins:lts
    privileged: true
    user: "root"
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

