version: '3'

services:
  nginx_single:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./src/web1/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf


  nginx_second:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./src/web2/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf

