services:
# Using nginx as proxy server only and redirect traffic to web1 or web2 container
  lb:
    image: nginx:latest
    ports:
    # Inbound port 1000 -> 80 port on container
      - 8080:80
    volumes:
      - ./nginxlb.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3

  web1:
    # define image version
    image: web1:v0.1.3
    
    build:
      context: .
      dockerfile: Dockerfile.web1

    ports:
    # Inbound port 8081 -> 80 port on container
      - 8081:80
    # volumes:
    #   - ./web1/index.html:/usr/share/nginx/html/index.html
    #   - ./nginx.conf:/etc/nginx/nginx.conf

  web2:
    # Using docker image web1:v0.1.3 to create container web2
    image: web1:v0.1.3
    ports:
      - 8082:80

  web3:
    # Using docker imnage web1:v0.1.3 to create container web3
    image: web1:v0.1.3
    ports:
      - 8083:80

    