services:
# Using nginx as proxy server only and redirect traffic to web1 or web2 container
  lb:
    image: nginx:latest
    ports:
    # Inbound port 1000 -> 80 port on container
      - 1000:80
    volumes:
      - ./nginxlb.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
      - web3

  web1:
    image: nginx:latest
    ports:
    # Inbound port 8081 -> 80 port on container
      - 8081:80
    volumes:
      - ./src/web1/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf


  web2:
    image: nginx:latest
    ports:
    # Inbound port 8082 -> 80 port on container
      - 8082:80
    volumes:
      - ./src/web2/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf

  web3:
    image: nginx:latest
    ports:
    # Inbound port 8083 -> 80 port on container
      - 8083:80
    volumes:
      - ./src/web3/index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
